script:
    log_file_name: NHLTwitterBot
    event_timeout: 300

default:
    team_name: New Jersey Devils

endpoints:
    nhl_base: http://statsapi.web.nhl.com
    nhl_endpoint: http://statsapi.web.nhl.com/api/v1
    nhl_rpt_base: http://www.nhl.com/stats/rest/team
    twitter_url: https://twitter.com/NJDevilsGameBot/status/
    twitter_handle: NJDevilsGameBot
    debug_twitter_handle: DevilsBotDebug

discord:
    debug_channel_id: 513415230026547202
    channel_id: 493573741167771649
