script:
    log_file_name: NHLTwitterBot
    event_timeout: 300
    preview_sleep_time: 1800
    pregame_sleep_time: 15
    live_sleep_time: 4
    intermission_sleep_time: 60
    final_sleep_time: 10

default:
    team_name: New Jersey Devils

endpoints:
    nhl_base: https://statsapi.web.nhl.com
    nhl_endpoint: https://statsapi.web.nhl.com/api/v1
    nhl_rpt_base: https://api.nhle.com/stats/rest/team
    twitter_url: https://twitter.com/NJDevilsGameBot/status/
    twitter_handle: NJDevilsGameBot
    debug_twitter_handle: DevilsBotDebug
    df_starting_goalies: https://www.dailyfaceoff.com/starting-goalies/
    # df_starting_goalies: https://www.dailyfaceoff.com/starting-goalies/09-17-2019/
    df_line_combos: https://www.dailyfaceoff.com/teams/TEAMNAME/line-combinations/
    hockeyref_base: https://www.hockey-reference.com/players
    scouting_refs: http://scoutingtherefs.com/wp-json/wp/v2/posts
    nst: https://www.naturalstattrick.com
    hockey_stat_cards: https://api.hockeystatcards.com/webapi

socials:
    twitter: True
    discord: True
    slack: False

twitter:
    prod:
        consumer_key: XXX
        consumer_secret: XXX
        access_token: XXX
        access_key: XXX
        handle: NJDevilsGameBot
    debug:
        consumer_key: r6RvF8KBaXGKNF7lPqi5Fpd4D
        consumer_secret: aABYmB7j3vILxlJTeOafjGA8Wd6pnwCt0C3zRBLAOBa1dm3UkA
        access_token: 959083884356014081-BISRbXsBcBE9L9wHwKgWsbs9K8DAnER
        access_secret: s2qF4ASiHDCxco1w7RlkYF82BMTPeeFfR4BAasArqlKg6
        handle: DevilsBotDebug

discord:
    prod:
        webhook_url: https://discordapp.com/api/webhooks/623596567797956609/dNdpsslQmb2DPzpfB27XA4tSpdLXcFMVck6xBZMhrZDVRKw7DVnbs0sYVLpMUr8yodS7
    debug:
        webhook_url: https://discordapp.com/api/webhooks/598249291265343488/mEeBlnlnJrvGSOrVRYXE_tChuaqpPe_5BMMMsqGfoQou88E8ZjiP82HBpu8UW3RC0CxK
