script:
    log_file_name: NHLTwitterBot
    event_timeout: 300
    preview_sleep_time: 1800
    pregame_sleep_time: 10
    live_sleep_time: 5
    final_sleep_time: 10

default:
    team_name: New Jersey Devils

endpoints:
    nhl_base: https://statsapi.web.nhl.com
    nhl_endpoint: https://statsapi.web.nhl.com/api/v1
    nhl_rpt_base: https://api.nhle.com/stats/rest/team
    twitter_url: https://twitter.com/NJDevilsGameBot/status/
    twitter_handle: NJDevilsGameBot
    debug_twitter_handle: DevilsBotDebug

events:
    gamecenterGameScheduled: GenericEvent
    gamecenterPeriodReady: Period
    gamecenterPeriodStart: Period
    gamecenterFaceoff: Faceoff
    gamecenterHit: Hit
    gamecenterStop: Stop
    gamecenterGoal: Goal
    gamecenterMissedShot: Shot
    gamecenterBlockedShot: Shot
    gamecenterGiveaway: GenericEvent
    gamecenterPenalty: Penalty
    gamecenterShot: Shot
    gamecenterTakeaway: GenericEvent
    gamecenterPeriodEnd: Period
    gamecenterPeriodOfficial: GenericEvent
    gamecenterGameEnd: GameEnd

discord:
    debug_channel_id: 513415230026547202
    channel_id: 493573741167771649
