script:
    log_file_name: NHLTwitterBot
    event_timeout: 300
    preview_sleep_time: 1800
    pregame_sleep_time: 15
    live_sleep_time: 5
    final_sleep_time: 10

default:
    team_name: New Jersey Devils

endpoints:
    nhl_base: https://statsapi.web.nhl.com
    nhl_endpoint: https://statsapi.web.nhl.com/api/v1
    nhl_rpt_base: https://api.nhle.com/stats/rest/team
    twitter_url: https://twitter.com/NJDevilsGameBot/status/
    twitter_handle: NJDevilsGameBot
    debug_twitter_handle: DevilsBotDebug
    # df_starting_goalies: https://www.dailyfaceoff.com/starting-goalies/
    df_starting_goalies: https://www.dailyfaceoff.com/starting-goalies/04-04-2019/
    df_line_combos: https://www.dailyfaceoff.com/teams/TEAMNAME/line-combinations/
    hockeyref_base: https://www.hockey-reference.com/players
    scouting_refs: http://scoutingtherefs.com/wp-json/wp/v2/posts

discord:
    debug_channel_id: 513415230026547202
    channel_id: 493573741167771649
